# Generated by Django 4.2.3 on 2023-07-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tag',
            field=models.ManyToManyField(blank=True, to='album.tag'),
        ),
    ]
