# Generated by Django 4.2.3 on 2023-07-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AddField(
            model_name='track',
            name='albums',
            field=models.ManyToManyField(related_name='tracks', to='album.album'),
        ),
    ]
