# Generated by Django 4.2.3 on 2023-07-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_rename_albums_track_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='track',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='track',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
