# Generated by Django 4.2.3 on 2023-07-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_track_created_at_remove_track_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.AlterField(
            model_name='track',
            name='number',
            field=models.IntegerField(),
        ),
    ]
